# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammerProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
    ]
