# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammerProfile', '0002_auto_20170328_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Description',
            field=models.TextField(default='lol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Name',
            field=models.CharField(default='lol', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
