# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammerProfile', '0004_person_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
