# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammerProfile', '0005_auto_20170329_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='Language',
            new_name='Lang',
        ),
    ]
