# Generated by Django 2.0 on 2018-03-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammerProfile', '0006_auto_20170329_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('post', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterField(
            model_name='person',
            name='ProfilePic',
            field=models.FileField(upload_to=''),
        ),
    ]
