# Generated by Django 2.0 on 2018-03-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammerProfile', '0007_auto_20180304_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='Name',
            field=models.CharField(max_length=1000000000000),
        ),
    ]
